"""tambah kolom tempat_lahir di tabel calon_siswa

Revision ID: 1d8e92fff8e0
Revises: 78176d22ea80
Create Date: 2026-05-25 20:04:11.594244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8e92fff8e0'
down_revision = '78176d22ea80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calon_siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempat_lahir', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calon_siswa', schema=None) as batch_op:
        batch_op.drop_column('tempat_lahir')

    # ### end Alembic commands ###
