"""hapus kolom redundan di tabel siswa

Revision ID: 363ed7b36743
Revises: 1d8e92fff8e0
Create Date: 2026-05-26 18:55:53.891816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363ed7b36743'
down_revision = '1d8e92fff8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calon_siswa', schema=None) as batch_op:
        batch_op.alter_column('pendaftaran_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('calon_siswa_pendaftaran_id_foreign'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pendaftaran', ['pendaftaran_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calon_siswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('calon_siswa_pendaftaran_id_foreign'), 'pendaftaran', ['pendaftaran_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('pendaftaran_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
